common lib for etl

diff --git a/.github/workflows/build-sub-projects.yml b/.github/workflows/build-sub-projects.yml
--- a/.github/workflows/build-sub-projects.yml
+++ b/.github/workflows/build-sub-projects.yml
@@ -84,6 +84,50 @@ jobs:
           git add .
           git commit -s -m "chore: self mutation"
           git push origin HEAD:$PULL_REQUEST_REF
+  build-etl-common:
+    name: build etl common library
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'corretto'
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v3
+        with:
+          gradle-version: 7.6
+      - name: Build & Test etl common library
+        run: |-
+          cd ./src/data-pipeline/etl-common
+          gradle clean build
+          gradle jacocoAggregatedReport
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: Test results for etl common library
+          report_paths: './src/data-pipeline/etl-common/build/test-results/test/TEST-*.xml'
+          fail_on_failure: true
+          require_tests: true
+          detailed_summary: true
+          job_name: build etl common library
+          update_check: true
+          include_passed: true
+      - name: Add coverage to PR
+        id: jacoco
+        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
+        uses: madrapps/jacoco-report@v1.6.1
+        with:
+          paths: ./src/data-pipeline/etl-common/build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          title: Etl common library's test coverage
+          min-coverage-overall: 80
+          min-coverage-changed-files: 80
+  
   build-data-pipeline:
     name: build data pipeline
     runs-on: ubuntu-latest
@@ -102,7 +146,9 @@ jobs:
           gradle-version: 7.6
       - name: Build & Test data pipeline spark application
         run: |-
-          cd ./src/data-pipeline/spark-etl
+          cd ./src/data-pipeline/etl-common
+          gradle clean install
+          cd ../spark-etl
           gradle clean build
           gradle jacocoAggregatedReport
       - name: Publish Test Report
