merge from main branch

diff --git a/.github/workflows/build-sub-projects.yml b/.github/workflows/build-sub-projects.yml
--- a/.github/workflows/build-sub-projects.yml
+++ b/.github/workflows/build-sub-projects.yml
@@ -14,13 +14,16 @@ jobs:
       - uses: actions/checkout@v4
       - uses: actions/setup-node@v4
         with:
-          node-version: "16"
+          node-version: 18.17.0
       - run: |-
+          npm install -g pnpm@8.15.3
+          pnpm install
+          pnpm projen
+          pnpm nx run-many --target=build
           cd frontend/
-          yarn install --check-files --frozen-lockfile
-          yarn run format
-          yarn run build
-          yarn run test
+          pnpm run format
+          pnpm run build
+          pnpm run test
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@v4
         if: success() || failure() # always run even if the previous step fails
@@ -40,7 +43,7 @@ jobs:
           git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT
       - name: Upload patch
         if: steps.self_mutation.outputs.self_mutation_happened
-        uses: actions/upload-artifact@v3
+        uses: actions/upload-artifact@v4
         with:
           name: .repo.patch
           path: .repo.patch
@@ -64,7 +67,7 @@ jobs:
           ref: ${{ github.event.pull_request.head.ref }}
           repository: ${{ github.event.pull_request.head.repo.full_name }}
       - name: Download patch
-        uses: actions/download-artifact@v3
+        uses: actions/download-artifact@v4
         with:
           name: .repo.patch
           path: ${{ runner.temp }}
@@ -81,6 +84,50 @@ jobs:
           git add .
           git commit -s -m "chore: self mutation"
           git push origin HEAD:$PULL_REQUEST_REF
+  build-etl-common:
+    name: build etl common library
+    runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'corretto'
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v3
+        with:
+          gradle-version: 7.6
+      - name: Build & Test etl common library
+        run: |-
+          cd ./src/data-pipeline/etl-common
+          gradle clean build
+          gradle jacocoAggregatedReport
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: Test results for etl common library
+          report_paths: './src/data-pipeline/etl-common/build/test-results/test/TEST-*.xml'
+          fail_on_failure: true
+          require_tests: true
+          detailed_summary: true
+          job_name: build etl common library
+          update_check: true
+          include_passed: true
+      - name: Add coverage to PR
+        id: jacoco
+        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
+        uses: madrapps/jacoco-report@v1.6.1
+        with:
+          paths: ./src/data-pipeline/etl-common/build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          title: Etl common library's test coverage
+          min-coverage-overall: 80
+          min-coverage-changed-files: 80
+  
   build-data-pipeline:
     name: build data pipeline
     runs-on: ubuntu-latest
@@ -88,18 +135,20 @@ jobs:
       pull-requests: write
     steps:
       - uses: actions/checkout@v4
-      - name: Set up JDK 11
+      - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
-          java-version: '11'
+          java-version: '17'
           distribution: 'corretto'
       - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
+        uses: gradle/gradle-build-action@v3
         with:
           gradle-version: 7.6
       - name: Build & Test data pipeline spark application
         run: |-
-          cd ./src/data-pipeline/spark-etl
+          cd ./src/data-pipeline/etl-common
+          gradle clean install
+          cd ../spark-etl
           gradle clean build
           gradle jacocoAggregatedReport
       - name: Publish Test Report
@@ -124,9 +173,12 @@ jobs:
           title: Data Pipeline spark application's test coverage
           min-coverage-overall: 80
           min-coverage-changed-files: 80
-  build-data-pipeline-example:
-    name: build data pipeline example
+  
+  build-streaming-ingestion:
+    name: build streaming ingestion
     runs-on: ubuntu-latest
+    permissions:
+      pull-requests: write
     steps:
       - uses: actions/checkout@v4
       - name: Set up JDK 11
@@ -135,7 +187,49 @@ jobs:
           java-version: '11'
           distribution: 'corretto'
       - name: Setup Gradle
-        uses: gradle/gradle-build-action@v2
+        uses: gradle/gradle-build-action@v3
+        with:
+          gradle-version: 7.6
+      - name: Build & Test streaming ingestion flink application
+        run: |-
+          cd ./src/streaming-ingestion/flink-etl
+          gradle clean build
+          gradle jacocoAggregatedReport
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          check_name: Test results for streaming ingestion flink application
+          report_paths: './src/streaming-ingestion/flink-etl/build/test-results/test/TEST-*.xml'
+          fail_on_failure: true
+          require_tests: true
+          detailed_summary: true
+          job_name: build streaming ingestion
+          update_check: true
+          include_passed: true
+      - name: Add coverage to PR
+        id: jacoco
+        if: github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name
+        uses: madrapps/jacoco-report@v1.6.1
+        with:
+          paths: ./src/streaming-ingestion/flink-etl/build/reports/jacoco/jacocoAggregatedReport/jacocoAggregatedReport.xml
+          token: ${{ secrets.GITHUB_TOKEN }}
+          title: Streaming ingestion flink application's test coverage
+          min-coverage-overall: 80
+          min-coverage-changed-files: 80
+
+  build-data-pipeline-example:
+    name: build data pipeline example
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Set up JDK 17
+        uses: actions/setup-java@v4
+        with:
+          java-version: '17'
+          distribution: 'corretto'
+      - name: Setup Gradle
+        uses: gradle/gradle-build-action@v3
         with:
           gradle-version: 7.6
       - name: Build & Test data pipeline examples
