chore: reduce create pipeline validation cognitive complexity and format frontend code

diff --git a/.github/workflows/build-sub-projects.yml b/.github/workflows/build-sub-projects.yml
--- a/.github/workflows/build-sub-projects.yml
+++ b/.github/workflows/build-sub-projects.yml
@@ -3,7 +3,7 @@ on:
   pull_request: {}
   workflow_dispatch: {}
 jobs:
-  build-frontend:
+  buildFrontend:
     name: build frontend
     runs-on: ubuntu-latest
     permissions:
@@ -17,6 +17,7 @@ jobs:
       - run: |-
           cd frontend/
           yarn install --check-files --frozen-lockfile
+          yarn run format
           yarn run build
           yarn run test
       - name: Publish Test Report
@@ -31,6 +32,54 @@ jobs:
           job_name: build frontend
           update_check: true
           include_passed: true
+      - name: Find mutations
+        id: self_mutation
+        run: |-
+          git add .
+          git diff --staged --patch --exit-code > .repo.patch || echo "self_mutation_happened=true" >> $GITHUB_OUTPUT
+      - name: Upload patch
+        if: steps.self_mutation.outputs.self_mutation_happened
+        uses: actions/upload-artifact@v3
+        with:
+          name: .repo.patch
+          path: .repo.patch
+      - name: Fail build on mutation
+        if: steps.self_mutation.outputs.self_mutation_happened
+        run: |-
+          echo "::error::Files were changed during build (see build log). If this was triggered from a fork, you will need to update your branch."
+          cat .repo.patch
+          exit 1
+  self-mutation:
+    needs: buildFrontend
+    runs-on: ubuntu-latest
+    permissions:
+      contents: write
+    if: always() && needs.buildFrontend.outputs.self_mutation_happened && !(github.event.pull_request.head.repo.full_name != github.repository)
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          token: ${{ secrets.PROJEN_GITHUB_TOKEN }}
+          ref: ${{ github.event.pull_request.head.ref }}
+          repository: ${{ github.event.pull_request.head.repo.full_name }}
+      - name: Download patch
+        uses: actions/download-artifact@v3
+        with:
+          name: .repo.patch
+          path: ${{ runner.temp }}
+      - name: Apply patch
+        run: '[ -s ${{ runner.temp }}/.repo.patch ] && git apply ${{ runner.temp }}/.repo.patch || echo "Empty patch. Skipping."'
+      - name: Set git identity
+        run: |-
+          git config user.name "github-actions"
+          git config user.email "github-actions@github.com"
+      - name: Push changes
+        env:
+          PULL_REQUEST_REF: ${{ github.event.pull_request.head.ref }}
+        run: |-
+          git add .
+          git commit -s -m "chore: self mutation"
+          git push origin HEAD:$PULL_REQUEST_REF
   build-data-pipeline:
     name: build data pipeline
     runs-on: ubuntu-latest
